---
# playbook to remove vSRX cloudformation template
- name: Ansible CloudFormation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: remove CloudFormation stack {{ stack_name }}
      cloudformation:
        state: absent
        stack_name: "{{ stack_name }}"
        region: eu-west-1
